# Generated by Django 6.0.3 on 2026-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.TextField(),
        ),
    ]
